# docker-compose.yml
version: '3'

services:
  aotd_frontend:
    build: Streamlit
    ports:
      - 8501:8501
    depends_on:
      - aotd_backend
    volumes:
      - ./Streamlit:/app
    environment:
      REQUESTS_URL: http://aotd_backend:8000

  aotd_backend:
    build: FastAPI
    ports:
      - 8000:8000
    env_file:
      - ./config.env # configure postgres
    volumes:
      - ./FastAPI:/app

  aotd_db:
    image: "postgres" # use latest official postgres version
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    env_file:
      - ./db.env # configure postgres
    ports:
      - 5432:5432

  aotd_app:
    image: aotd_app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./config.env # configure postgres
    volumes:
      - ./:/app

volumes:
  db: # named volumes can be managed easier using docker-compose
